#include "slicePlots.h"
#include "simplePlots.h"
#include "effiPlots.h"
#include "cutFlow.h"

#include "TFile.h"

#include <iostream>


using namespace std;

int main(){

  //FastFullSim Comparison METCheck
  simplePlots METCheck("plots/METCHECK.ps");
  METCheck.addFile("/afs/cern.ch/work/d/dagonzal/public/CMSSW_8_0_0_pre2/src/Check/METCHECK/python/FullSim_RelValSMS-T1tttt_mGl-1500_mLSP-100_13.root");
  METCheck.addFile("/afs/cern.ch/work/d/dagonzal/public/CMSSW_8_0_0_pre2/src/Check/METCHECK/python/FastSim_RelValSMS-T1tttt_mGl-1500_mLSP-100_13.root");
  METCheck.setLegend(0.25,0.6,0.85,0.8);
  METCheck.loadHists("gen_trueMET");
  //METCheck.loadHists("CaloMET");
  METCheck.addLegendEntry("true MET FullSim SUSY");
  METCheck.addLegendEntry("true MET FastSim SUSY");
  METCheck.normToArea(true,0.4);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("PFMET");
  METCheck.addLegendEntry("PF MET FullSim SUSY");
  METCheck.addLegendEntry("PF MET FastSim SUSY");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("gen_caloMET");
  METCheck.addLegendEntry("Gen Calo MET FullSim SUSY");
  METCheck.addLegendEntry("Gen Calo MET FastSim SUSY");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("CaloMET");
  METCheck.addLegendEntry("Calo MET FullSim SUSY");
  METCheck.addLegendEntry("Calo MET FastSim SUSY");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("GenMinusPFMET");
  METCheck.addLegendEntry("(trueMET-PFMET).M() FullSim SUSY");
  METCheck.addLegendEntry("(trueMET-PFMET).M() FastSim SUSY");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("pf_pt");
  METCheck.addLegendEntry("PF pt FullSim SUSY");
  METCheck.addLegendEntry("PF pt FastSim SUSY");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("chargedPf_pt");
  METCheck.addLegendEntry("charged PF pt FullSim SUSY");
  METCheck.addLegendEntry("charged PF pt FastSim SUSY");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("neutralPf_pt");
  METCheck.addLegendEntry("neutral PF pt FullSim SUSY");
  METCheck.addLegendEntry("neutral PF pt FastSim SUSY");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();

  METCheck.clearFiles();
  METCheck.addFile("/afs/cern.ch/work/d/dagonzal/public/CMSSW_8_0_0_pre2/src/Check/METCHECK/python/FullSim_RelValQCD_FlatPt_15_3000HS_13.root");
  METCheck.addFile("/afs/cern.ch/work/d/dagonzal/public/CMSSW_8_0_0_pre2/src/Check/METCHECK/python/FastSim_RelValQCD_FlatPt_15_3000_13.root");
  METCheck.setLegend(0.25,0.6,0.85,0.8);
  METCheck.loadHists("gen_trueMET");
  //METCheck.loadHists("CaloMET");
  METCheck.addLegendEntry("true MET FullSim QCD");
  METCheck.addLegendEntry("true MET FastSim QCD");
  METCheck.normToArea(true,0.4);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("PFMET");
  METCheck.addLegendEntry("PF MET FullSim QCD");
  METCheck.addLegendEntry("PF MET FastSim QCD");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("gen_caloMET");
  METCheck.addLegendEntry("Gen Calo MET FullSim QCD");
  METCheck.addLegendEntry("Gen Calo MET FastSim QCD");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("CaloMET");
  METCheck.addLegendEntry("Calo MET FullSim QCD");
  METCheck.addLegendEntry("Calo MET FastSim QCD");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("GenMinusPFMET");
  METCheck.addLegendEntry("(trueMET-PFMET).M() FullSim QCD");
  METCheck.addLegendEntry("(trueMET-PFMET).M() FastSim QCD");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("pf_pt");
  METCheck.addLegendEntry("PF pt FullSim QCD");
  METCheck.addLegendEntry("PF pt FastSim QCD");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("chargedPf_pt");
  METCheck.addLegendEntry("charged PF pt FullSim QCD");
  METCheck.addLegendEntry("charged PF pt FastSim QCD");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("neutralPf_pt");
  METCheck.addLegendEntry("neutral PF pt FullSim QCD");
  METCheck.addLegendEntry("neutral PF pt FastSim QCD");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();

  METCheck.clearFiles();
  METCheck.addFile("/afs/cern.ch/work/d/dagonzal/public/CMSSW_8_0_0_pre2/src/Check/METCHECK/python/FullSim_RelValTTbar_13.root");
  METCheck.addFile("/afs/cern.ch/work/d/dagonzal/public/CMSSW_8_0_0_pre2/src/Check/METCHECK/python/FastSim_RelValTTbar_13.root");
  METCheck.setLegend(0.25,0.6,0.85,0.8);
  METCheck.loadHists("gen_trueMET");
  //METCheck.loadHists("CaloMET");
  METCheck.addLegendEntry("true MET FullSim TT");
  METCheck.addLegendEntry("true MET FastSim TT");
  METCheck.normToArea(true,0.4);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("PFMET");
  METCheck.addLegendEntry("PF MET FullSim TT");
  METCheck.addLegendEntry("PF MET FastSim TT");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("gen_caloMET");
  METCheck.addLegendEntry("Gen Calo MET FullSim TT");
  METCheck.addLegendEntry("Gen Calo MET FastSim TT");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("CaloMET");
  METCheck.addLegendEntry("Calo MET FullSim TT");
  METCheck.addLegendEntry("Calo MET FastSim TT");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.setLegend(0.25,0.6,0.85,0.8);
  METCheck.loadHists("GenMinusPFMET");
  METCheck.addLegendEntry("(trueMET-PFMET).M() FullSim TT");
  METCheck.addLegendEntry("(trueMET-PFMET).M() FastSim TT");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("pf_pt");
  METCheck.addLegendEntry("PF pt FullSim TT");
  METCheck.addLegendEntry("PF pt FastSim TT");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("chargedPf_pt");
  METCheck.addLegendEntry("charged PF pt FullSim TT");
  METCheck.addLegendEntry("charged PF pt FastSim TT");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();
  METCheck.loadHists("neutralPf_pt");
  METCheck.addLegendEntry("neutral PF pt FullSim TT");
  METCheck.addLegendEntry("neutral PF pt FastSim TT");
  METCheck.normToArea(true,0.5);
  METCheck.setErrorBand(2,0);
  METCheck.plotHists(2,true);
  METCheck.clearHists();
  METCheck.clearLegend();



  return 0;
}
